### ISSUE TITLE
[Epic] Upgrade to v2

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/data-science-pipelines-operator#335]
Tekton V2: 

- [ ] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/432
- [ ] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/429
- [ ] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/428
- [x] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/427
- [x] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/425
- [x] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/377
- [x] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/369
- [ ] https://github.com/opendatahub-io/data-science-pipelines-operator/issues/445

**Comment by gregsheremeta** [comment]
Migrated to Jira: https://issues.redhat.com/browse/RHOAIENG-1665
